libsecril-shim: fix RIL_REQUEST_QUERY_AVAILABLE_NETWORKS
Remove the extra (unused) element from the operator info, freaking out the framework.
Formerly, this is know as the mQANElements override.

KitKat:
fix compiling:
device/samsung/espresso3g/rilsrc/libsecril-shim/secril-shim.h:37:5: error: unknown type name 'RIL_SOCKET_ID'

Also remove "int wasAckSent;"

Change-Id: I2f2ed984383a6656bfd39d419f0b8702d66a7e16