Update patch set 3
Patch Set 3: Code-Review-2

Need to look at it after sleep:

target thumb C: libsecril-shim <= device/samsung/espresso3g/rilsrc/libsecril-shim/secril-shim.c
target thumb C: libsqlite_jni <= external/javasqlite/src/main/native/sqlite_jni.c
target thumb C++: libsoundpool <= frameworks/base/media/jni/soundpool/android_media_SoundPool_SoundPoolImpl.cpp
Import includes file: /ssd2/out/aosp-5.1/target/product/espresso3g/obj/SHARED_LIBRARIES/libstagefright_soft_aacdec_intermediates/import_includes
device/samsung/espresso3g/rilsrc/libsecril-shim/secril-shim.c:9:59: error: unused parameter 'datalen' [-Werror,-Wunused-parameter]
static void onRequestDial(int request, void *data, size_t datalen, RIL_Token t) {
                                                          ^
device/samsung/espresso3g/rilsrc/libsecril-shim/secril-shim.c:86:92: error: unused parameter 'responselen' [-Werror,-Wunused-parameter]
static void onCompleteRequestGetSimStatus(RIL_Token t, RIL_Errno e, void *response, size_t responselen) {
                                                                                           ^
device/samsung/espresso3g/rilsrc/libsecril-shim/secril-shim.c:139:56: error: unused parameter 'responselen' [-Werror,-Wunused-parameter]
static void fixupSignalStrength(void *response, size_t responselen) {
                                                       ^
3 errors generated.
make: *** [/ssd2/out/aosp-5.1/target/product/espresso3g/obj/SHARED_LIBRARIES/libsecril-shim_intermediates/secril-shim.o] Error 1
make: *** Waiting for unfinished jobs....

Patch-set: 3
Label: Code-Review=-2